### ISSUE TITLE
why does MW have so few commits?

### ISSUE THREAD

**Issue by tofr** [MrEricL/heJEMony#3]

**Comment by matteowong** [comment]
Hi Mr. Brown,

When looking at the commits a lot of them are from my home machine. It seems that over the past couple of weeks something very strange happened where my machine's git email was switched from my stuy.edu to my personal email so all the commits are from an unknown author. I am going to fix that right now and give them the proper author.

**Comment by matteowong** [comment]
I just updated the commit logs. I ran a script found on the github help sight and replaced Matteo@Matteos-Macbook-Air.local with mwong8@stuy.edu
